### PR TITLE
Support to repository name including dots ( fixes #13 )

### LINKED ISSUE #13: It does not work in a repository that contains dots in the path/name.
In a repository such as `https://github.com/wraith13/wraith13.github.io`, it should be recognized as `wraith13/wraith13.github.io`, in fact it recognizes it as `wraith13/wraith13` and access failed To do.
vscode-github-issues-prs bug

### PR DESCRIPTION
**Pull request by wraith13**
I fixed #13 .
Let me know if there are any problem.

### CODE REVIEW

**Comment by chrmarti** [comment]
Would it be simpler to just match `.git` and then drop the following `[^\s]*`?

**Comment by wraith13** [comment]
Yes, I think so.

**Comment by chrmarti** [comment]
If you get a chance to update the PR, I'll be happy to merge it.

**Comment by wraith13** [comment]
Thanks!

**Comment by wraith13** [comment]
Sorry! I misunderstood that you said. ( My close friend informed to me. )
I will fix it later.

**Comment by wraith13** [comment]
I fixed. How about this?

**Comment by chrmarti** [comment]
Don't all GitHub remote's have the `.git` suffix? I thought `/[^\s]*github\.com[/:]([^/]+)\/([^ ]+)\.git/` might do it.

**Comment by wraith13** [comment]
Sorry, I am not familiar with git.
So, I took a safe way.

**Comment by wraith13** [comment]
https://stackoverflow.com/questions/2514859/regular-expression-for-git-repository
There seems to must be .git at the end of the path of the git repository.

**Comment by wraith13** [comment]
How about this time?

**Comment by chrmarti** [comment]
Looks good, except I just found a remote without the '.git' suffix. Maybe that has become optional at some point?

**Comment by wraith13** [comment]
I do not know. However, I think other tools also expect(need) '.git'.

First of all, in accordance with KISS principle, adopt this simple code.
We will respond if the complaint actually comes.
How about such a plan?

**Comment by chrmarti** [comment]
Let's remove `\.git` from the regex and then remove `.git` from the `owner` variable later if it is there. That's simple and I have a case where `.git` is missing myself.

**Comment by wraith13** [comment]
It's a `repo` instead of an `owner`, is it?
I fixed, how is this?

**Comment by chrmarti** [comment]
Thanks @wraith13 !

**Pull request merged**
