### PR TITLE
Add copy url #16

### PR DESCRIPTION
**Pull request by Ikuyadeu**
Related #16.
I added `copy summary` and `copy url` when right click issue.

### CODE REVIEW

**Comment by chrmarti** [comment]
Hi @Ikuyadeu, thanks for your contribution!

I can see the Copy URL action being useful. I'm not sure about Copy Summary, because that usually consists of many lines of description and if someone wants to copy from it they are likely to first look at it (on github.com in the browser) and then decide on whether to copy it full or in part. What do you think?

**Comment by Ikuyadeu** [comment]
@chrmarti Thank you for your review.
`Copy Summary` function is for user who doesn't want to switching code window to browser window.
I think some other solutions.
1. `Copy Summary` to `Copy Summary Header`, that can get summary's first line.
2. `Copy Summary` to `Preview Summary`, that open Markdown preview

**Comment by chrmarti** [comment]
I want to keep the functionality in the extension small and defer previewing of the summary to the website in the browser. I don't think opening the browser is a bad thing if it does not happen too often.

The current actions in the context menu provide shortcuts for things that do not require additional user interaction to be useful, that keeps the extension simple. Copy URL seems to fit that pattern, Copy Summary (or similar) needs something to preview/show the summary and does not seem to fit the pattern.

**Comment by Ikuyadeu** [comment]
@chrmarti Thank you for your suggestion. I understand.
So I will remove only `Copy Summary`.

**Comment by chrmarti** [comment]
@Ikuyadeu Great, happy to merge after that.

**Comment by Ikuyadeu** [comment]
@chrmarti OK, I fixed!

**Comment by chrmarti** [comment]
Thanks @Ikuyadeu !

**Pull request merged**
