### PR TITLE
Get NoMileStones and Set number of MileStones #4

### PR DESCRIPTION
**Pull request by Ikuyadeu**
Relate #4
This change added property `github.getNoMilestones`.

### CODE REVIEW

**Comment by chrmarti** [comment]
Thanks for submitting the PR @Ikuyadeu !

I'm wondering how we might address all concerns in https://github.com/Microsoft/vscode-github-issues-prs/issues/4#issuecomment-311413676. `github.getNoMilestones` wouldn't do that, maybe a more flexible setting would.

**Comment by Ikuyadeu** [comment]
@chrmarti Thank you for your Review!
How does this look? If you set `github.maxMilestones` you can get milestones all you want.

**Comment by chrmarti** [comment]
@Ikuyadeu Thanks for the update! I'm not sure yet if adding settings is the best way to go. Maybe we could just show all milestones and only expand the first (or first two) instead.

**Comment by Ikuyadeu** [comment]
@chrmarti OK, Should setting be only `MilestoneKind`  that has state only `All` or `Latest`?

**Comment by Ikuyadeu** [comment]
@chrmarti How is this? 
Now, you can get more MileStone each refresh.
But I think this should be called by icon instead of refresh.
What I should use icon images?

**Comment by chrmarti** [comment]
Found a better API to fetch all issues and pushed a change to master. Thanks for looking into this.

**Comment by Ikuyadeu** [comment]
Ok, thank you @chrmarti !

**Pull request closed without merging**
