### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by rebornix**
Fetch open pull requests of this repo. It's not the pull request filed by the owner.

### CODE REVIEW

**Comment by eamodio** [comment]
Any chance this will get integrated in the near future?

**Comment by chrmarti** [comment]
Unfortunately I hadn't had time to look into moving this forward.

**Comment by rebornix** [comment]
@chrmarti we can revisit this when the Pull Request/Comments feature is on our plan.

**Comment by chrmarti** [comment]
@rebornix I think this would be a valuable feature. Maybe I can find time to look into it before that. \<fingerscrossed>

**Comment by KamasamaK** [comment]
I take it this has been superseded by https://github.com/microsoft/vscode-pull-request-github

**Pull request closed without merging**
